---
   - hosts: docker-master
       
     tasks:
        - name: "Create folder java_maven_devops"
          file:
             path: $HOME/java_maven_devops
             state: directory

        - name: "Copy docker-compose"
          template:
             src: "{{ WORKSPACE }}/docker-compose.yml"
             dest: $HOME/java_maven_devops

        - name: "Install docker stack dep"
          pip:
            name: jsondiff, pyyaml
        
        - name: "Deploy deock-compose"
          docker_stack:
             state: present
             name: java_maven_devops
             compose:
                - $HOME/java_maven_devops/docker-compose.yml